### ISSUE TITLE
get json

### ISSUE THREAD

**Issue by vmwinckler** [mabako/steam-group-wishlist#5]
how can I extract the results in JSON? the script has this option? How should I proceed?

i try:

http://swl.mabako.net/giftofgiving/206420?json=1
http://swl.mabako.net/giftofgiving/206420/json

is there any way?

thank you

**Comment by mabako** [comment]
There is - currently - no API defined.

What in particular should the results contain, as in - data; wishlists, check if someone owns this? How should it be structured?

There is this little bit of a problem in that it would take ages, at least a few minutes of ever posting any JSON output as well. The browser version handles this by using `localStorage`, but there wouldn't be any caching for API calls.
